### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by viscuintcode** [corso-android-ivan-morgillo/team-c#157]
l'applicazione dovrebbe permettere di selezionare con quale account fare login dopo aver fatto il log out

**Comment by alaudiero** [comment]
The current solution permanently deletes the account from firestore, and when the user logs in again with the same account, they cannot get the favorites they had chosen.

Maybe we can try with the solution proposed here
https://stackoverflow.com/questions/38707133/google-firebase-sign-out-and-forget-user-in-android-app
