### ISSUE TITLE
Rimuovere commenti 

### ISSUE THREAD

**Issue by alaudiero** [corso-android-ivan-morgillo/team-c#62]
In MainviewModel rimuovere commenti a righe 18 e 25

**Comment by GiulyBlues** [comment]
/*when (states.value ){
                    // 4 scenari
                    is MainScreenStates.Content -> TODO("NON DOVREMMO FARE NIENTE") // l'utente chiude e apre l'app
                    MainScreenStates.Error -> TODO("FORSE SIAMO TORNATI NEL WIFI E ABBIAMO BISOGNO DELLA  LOADING")
                    MainScreenStates.Loading -> TODO("L'UTENTE è USCITO DALL'APP MENTRE STAVA ANCORA IN LOADING(!?)")
                    null -> TODO("da valutare lo stato iniziale della app")
                }*/
                // aggiungere exaustive
