### ISSUE TITLE
Sistemare schermata dettaglio 

### ISSUE THREAD

**Issue by GiulyBlues** [corso-android-ivan-morgillo/team-c#67]
![image](https://user-images.githubusercontent.com/53172351/107742234-f5753100-6d0e-11eb-9e25-5d012ded4a6e.png)
oppure 
![image](https://user-images.githubusercontent.com/53172351/107742275-0625a700-6d0f-11eb-80ac-07cdc505923d.png)

**Comment by alaudiero** [comment]
![image](https://user-images.githubusercontent.com/53529795/108080590-559e0700-7070-11eb-9173-f53db9301981.png)
